#!/sbin/sh

if [ -f /cache/oc ]; then 
	speed=`cat /cache/oc` 
	echo $speed > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 

fi
if [ ! -f /cache/oc ]; then
	echo "800000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 
fi
