#!/sbin/sh

PARTITION=$1
IMAGE=$2

if [ "$PARTITION" == "boot" ]; then
  if [ `cat /etc/recovery.fstab | grep boot | egrep -v "("fota"|"bootloader")" | awk '{print$2}'` == "mtd" ]; then
    BOOT_DEVICE="/dev/mtd/"`cat /proc/mtd | grep boot | egrep -v "("fota"|"bootloader")" | awk '{print$1}' | sed 's/://g'`
  else
    BOOT_DEVICE=`cat /etc/recovery.fstab | grep boot | egrep -v "("bootloader"|"fota_boot")" | awk '{print$3}'`
  fi

  dd if=$IMAGE of=$BOOT_DEVICE
  if [ $? -ne 0  ]; then
    flash_image $PARTITION $IMAGE
  fi
fi
[ $? -ne 0 ] && exit 1
[ $? -eq 0 ] && exit 0

if [ "$PARTITION" == "recovery" ]; then
  if [ `cat /etc/recovery.fstab | grep recovery | awk '{print$2}'` == "mtd" ]; then
    RECOVERY_DEVICE="/dev/mtd/"`cat /proc/mtd | grep recovery | awk '{print$1}' | sed 's/://g'`
  else
    RECOVERY_DEVICE=`cat /etc/recovery.fstab | grep recovery | awk '{print$3}'`
  fi

  dd if=$IMAGE of=$RECOVERY_DEVICE
  if [ $? -ne 0 ]; then
    flash_image $PARTITION $IMAGE
  fi
fi
[ $? -ne 0 ] && exit 1
[ $? -eq 0 ] && exit 0

  

